name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installer sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Déploiement
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /var/www/apiartisanvillage
        run: |
          # Installer l'extension intl et Composer sur le serveur distant
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo apt-get update &&
            sudo apt-get install -y php-intl &&
            sudo systemctl restart nginx &&
            composer --version || sudo apt-get install -y composer"
          # Créer les répertoires nécessaires sur le serveur distant et ajuster les permissions
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo mkdir -p $REMOTE_PATH &&
            sudo mkdir -p $REMOTE_PATH/storage &&
            sudo mkdir -p $REMOTE_PATH/bootstrap/cache &&
            sudo chown -R $REMOTE_USER:$REMOTE_USER $REMOTE_PATH &&
            sudo chmod -R 775 $REMOTE_PATH"
          # Copier les fichiers nécessaires
          sshpass -p "$SSH_PASSWORD" rsync -avz --exclude '.git' --exclude 'node_modules' --exclude '.env' . $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
          # Exécuter les commandes de déploiement à distance avec des permissions appropriées
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo ln -sf $REMOTE_PATH/docker/apiartisanvillage.conf /etc/nginx/sites-enabled/ &&
            cd $REMOTE_PATH &&
            sudo chown -R $REMOTE_USER:www-data storage bootstrap/cache &&
            sudo chmod -R 775 storage bootstrap/cache &&
            composer update --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            sudo systemctl restart nginx &&
            sudo certbot --nginx -d artisanvillage.fr -d www.artisanvillage.fr --non-interactive --agree-tos -m ludolpr@gmail.com"
