name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  post-deploy:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Finaliser le déploiement
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            # Déplacer le fichier de configuration Nginx
            sudo cp $REMOTE_PATH/docker/apiartisanvillage.conf /etc/nginx/sites-available/ &&
            sudo ln -sf /etc/nginx/sites-available/apiartisanvillage.conf /etc/nginx/sites-enabled/ &&
            # Installation des dépendances Composer et exécution des commandes Laravel
            cd $REMOTE_PATH &&
            sudo chmod -R 775 storage bootstrap/cache &&
            sudo chown -R www-data storage bootstrap/cache &&
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            # Redémarrage de Nginx
            sudo systemctl restart nginx &&
            # Configuration SSL avec Certbot
            sudo certbot --nginx -d artisanvillage.fr -d www.artisanvillage.fr --non-interactive --agree-tos -m ludolpr@gmail.com"
