name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installer sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Déployer les fichiers sur le serveur
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /home/${{ secrets.REMOTE_USER }}/apiartisanvillage
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            mkdir -p $REMOTE_PATH"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r * $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH

      - name: Déplacer les fichiers vers le répertoire souhaité
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /var/www/apiartisanvillage
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo mkdir -p $REMOTE_PATH &&
            sudo mv ~/apiartisanvillage/* $REMOTE_PATH &&
            sudo chown -R $REMOTE_USER:$REMOTE_USER $REMOTE_PATH &&
            sudo chmod -R 775 $REMOTE_PATH &&
            sudo chown -R www-data:www-data $REMOTE_PATH/storage $REMOTE_PATH/bootstrap/cache"
