name: CI-Artisan-village
# version:1 
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copier le fichier .env.docker
        run: |
          echo "DB_CONNECTION=mysql" >> ./docker/.env
          echo "DB_HOST=mysql" >> ./docker/.env
          echo "DB_PORT=3306" >> ./docker/.env
          echo "DB_DATABASE=testing" >> ./docker/.env
          echo "DB_USERNAME=root" >> ./docker/.env
          echo "DB_PASSWORD=root" >> ./docker/.env

      - name: Installer Docker
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Dormir pendant 10 secondes
        run: sleep 10s
        shell: bash

      - name: Initialiser les conteneurs
        run: |
          for i in {1..5}; do docker-compose up -d && break || sleep 15; done

      - name: Installer les dépendances Composer
        run: docker exec apiArtisanVillage bash -c "composer install"

      - name: Migrer la base de données
        run: docker exec apiArtisanVillage bash -c "php artisan migrate --force"

      - name: Peupler la base de données
        run: docker exec apiArtisanVillage bash -c "php artisan db:seed --force"

      - name: Migrer la base de données de test
        run: docker exec apiArtisanVillage bash -c "php artisan migrate --env=testing --force"

      - name: Exécuter les tests PHPUnit
        run: docker exec apiArtisanVillage bash -c "php artisan test tests/Feature"
