name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installer sshpass et rsync
        run: sudo apt-get update && sudo apt-get install -y sshpass rsync

      - name: Configurer Docker
        run: |
          mkdir -p ./docker
          echo "DB_CONNECTION=mysql" > ./docker/.env
          echo "DB_HOST=mysql" >> ./docker/.env
          echo "DB_PORT=3306" >> ./docker/.env
          echo "DB_DATABASE=testing" >> ./docker/.env
          echo "DB_USERNAME=root" >> ./docker/.env
          echo "DB_PASSWORD=root" >> ./docker/.env

      - name: Déploiement avec `rsync`
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /var/www/apiartisanvillage
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo mkdir -p $REMOTE_PATH &&
            sudo chown -R $REMOTE_USER:$REMOTE_USER $REMOTE_PATH &&
            sudo chmod -R 775 $REMOTE_PATH"
          sshpass -p "$SSH_PASSWORD" rsync -avz --delete --exclude '.git' --exclude 'node_modules' --exclude '.env' . $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            cd $REMOTE_PATH &&
            sudo chown -R $REMOTE_USER:www-data storage &&
            sudo chmod -R 775 storage &&
            ln -sf /etc/nginx/sites-available/apiartisanvillage.conf /etc/nginx/sites-enabled/ &&
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            sudo systemctl restart nginx &&
            sudo certbot --nginx -d artisanvillage.fr -d www.artisanvillage.fr --non-interactive --agree-tos -m ludolpr@gmail.com"
