name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Deploiement
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /var/www/apiartisanvillage
        run: |
          # Installer sshpass pour l'authentification par mot de passe
          sudo apt-get update && sudo apt-get install -y sshpass
          # Copier les fichiers nécessaires uniquement
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./docker/.env $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/docker/
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./src $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/src
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r ./public $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH/public
          # Exécuter les commandes de déploiement à distance
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            cd $REMOTE_PATH &&
            ln -sf /etc/nginx/sites-available/apiartisanvillage.conf /etc/nginx/sites-enabled/ &&
            composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            sudo systemctl restart nginx &&
            sudo certbot --nginx -d artisanvillage.fr -d www.artisanvillage.fr --non-interactive --agree-tos -m ludolpr@gmail.com"
