name: CI/CD-Artisan-village

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installer sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Déployer les fichiers sur le serveur
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r * $REMOTE_USER@$REMOTE_HOST:~

      - name: Déplacer les fichiers vers le répertoire souhaité
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PATH: /var/www/apiartisanvillage
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "
            sudo mkdir -p $REMOTE_PATH &&
            sudo mv ~/docker $REMOTE_PATH &&
            sudo mv ~/public $REMOTE_PATH &&
            sudo mv ~/resources $REMOTE_PATH &&
            sudo mv ~/routes $REMOTE_PATH &&
            sudo mv ~/storage $REMOTE_PATH &&
            sudo mv ~/tests $REMOTE_PATH &&
            sudo mv ~/vendor $REMOTE_PATH &&
            sudo mv ~/artisan $REMOTE_PATH &&
            sudo mv ~/composer.json $REMOTE_PATH &&
            sudo mv ~/composer.lock $REMOTE_PATH &&
            sudo mv ~/package.json $REMOTE_PATH &&
            sudo mv ~/phpunit.xml $REMOTE_PATH &&
            sudo mv ~/postman_collection.json $REMOTE_PATH &&
            sudo mv ~/vite.config.js $REMOTE_PATH &&
            sudo chown -R $REMOTE_USER:$REMOTE_USER $REMOTE_PATH &&
            sudo chmod -R 775 $REMOTE_PATH &&
            sudo chown -R www-data:www-data $REMOTE_PATH/storage $REMOTE_PATH/bootstrap/cache
          "
